### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by blasco** [angular/preboot#117]
Is this repository dead? If this is the case, what alternatives are there? I cannot find a way to get rid of the flicker after page load. ngIf in templates do not wait for the state being transferred by angular universal.

**Comment by CaerusKaru** [comment]
Not as much as I'd like, but I'm committed to getting a v11 release done, see [here](https://github.com/angular/preboot/pull/118)

**Comment by blasco** [comment]
Great, it is quiet unfortunate as I think there is really a huge problem with the transition from server to browser.  Transfer state doesn't solve most of the issues, and so far I know there is no easy way to delay the rendering of the templates and avoid destroying the dom transferred by the server.
