### ISSUE TITLE
provide option to manually complete preboot

### ISSUE THREAD

**Issue by gdi2290** [angular/preboot#16]
`preboot.complete()`

right now it checks for `document.body` then creates a loop using `setTimeout`

**Comment by jeffwhelpley** [comment]
Do you mean init()? preboot.complete() is only in the browser code and shouldn't be inlined.

**Comment by gdi2290** [comment]
How do you tell preboot to swap the views once the framework is ready. For example, on mobile if you're typing in an input and the client is bootstrapped you want to avoid doing dom until focus change or enter. You need to do this to avoid the keyboard showing up twice during the swap.

**Comment by jeffwhelpley** [comment]
OK, so you are right for this particular situation where we want to defer preboot.complete() we will need to make an adjustment. @gdi2290 I don't suggest you stop from your integration with universal and updates to rc5. I will add a fix for this once I get back next week. Let me know, though, if there is something that is actually blocking you. Understood about this use case, but other than that, things should be fine.

**Comment by gdi2290** [comment]
how do I remove the loading overlay without `preboot.complete()`?
https://github.com/angular/preboot/blob/e372ae16fc6c74d315e7e909f4cf3c6764fd85bc/src/inline/preboot_inline.ts#L287...L290

**Comment by jeffwhelpley** [comment]
@gdi2290 FYI, I just published a new version of preboot that should have all you need.

To start preboot via inline code, most of the time you just call `init()` and let it loop until the DOM is ready, BUT if you want to do it manually, simply add `start()` right after `init()`. I added something to `start()` that ensures it will only run the preboot start code once so you can call it as many times as you want without issues....however, if you call it manually, just make sure the DOM really is available first yourself.

To complete preboot you call `complete()` with the browser code lib. This will call `cleanup()` under the scenes which now calls `removeOverlay(window)`. If you want to just remove the overlay without completing or cleaning up, just call `removeOverlay(window)` directly.

Let me know if this makes sense.

**Comment by gdi2290** [comment]
@jeffwhelpley what version of preboot has complete?

**Comment by jeffwhelpley** [comment]
Use `4.5.2`. Note, however, that `complete()` is on the preboot browser code, NOT the inline code. To call this you have to do:

```
import {prebootClient} from 'preboot';
var preboot = prebootClient();
preboot.complete();
```

I know the API is a little wonky but that ultimately is because I wanted to avoid downstream dependencies in the preboot lib. So, the browser code is very simply one exported function. Just use this for now and we can work on potential API improvements later.

**Comment by gdi2290** [comment]
how do I determine if there isn't preboot inlined?

**Comment by gdi2290** [comment]
prebootClient doesn't work since it's not exporting anything

**Comment by gdi2290** [comment]
I'm importing __build/src/browser/preboot_browser for now

**Comment by jeffwhelpley** [comment]
Right...you can't do `var preboot = prebootClient();` ?

**Comment by jeffwhelpley** [comment]
Closing this as you can manually call `complete()` now.

**Comment by Flood** [comment]
How can we call `complete()` on preboot 5.0.0? Using Angular 4.3.x

Seems that it's never called for me. I am using angular universal and the server rendered version looks good, but when it swaps I'll get two <app> instances, where the client version is `display:none` and the second version is missing some css.

**Comment by jeffwhelpley** [comment]
@Flood ignore what is said earlier in this issue because the API for preboot 5+ is different. So, if you wanted preboot to automatically complete you would do this:

https://github.com/angular/preboot/blob/master/test/e2e/e2e.browser.module.ts#L14

If you want to manually complete simply change the preboot module reference to:

```
BrowserPrebootModule.replayEvents({ noReplay: true })
```

then somewhere else in your code (up to you decide where and when you do this), you would inject the EventReplayer like this:

```
@Injectable()
export class Something {
  constructor(eventReplayer: EventReplayer) {
    eventReplayer. replayAll();
  }
}
```
