### ISSUE TITLE
Documentation 404, not found.

### ISSUE THREAD

**Issue by mozqt** [angular/preboot#25]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [x] docs
- [ ] tests

* **What is the current behavior?**

Documentation gives 404, not found.
eg. https://universal.angular.io/api/preboot/docs/strategies.md#listen-strategies

**Comment by jeffwhelpley** [comment]
I removed documentation other than the README but I added more information there. Let me know if that doesn't make sense.
