### ISSUE TITLE
inject inlinePrebootCode in HEAD? or immediately after appRoot

### ISSUE THREAD

**Issue by jotto** [angular/preboot#27]
* **I'm submitting a ...**
- [x] bug report

* **Which parts of preboot are affected by this issue?**
- [x] server side
- [x] inline

According to the README:

> You then inject inlinePrebootCode into the HEAD section of your server-side template.

But that doesn't work, at least, in the following cases:

* With Angular 2x auto bootstrap (using `ng-app` or `data-ng-app` attr on your app root), this inline script seems to only work at the very end of the `<body>` (presumably because Angular waits for DOM ready event before executing)
  * in other words, the [`waitUntilReady`](https://github.com/angular/preboot/blob/ff24ce4949a485703c7ede471c48beb8d79f6cda/src/inline/preboot_inline.ts#L74-L80) must not (even with setTimeout of 1) be getting executed fast enough
* With Angular 4x, where Angular's `bootstrapModule` code can happen before DOM ready event, then this inline script only works when _immediately_ after the app root.

So I'm proposing, assuming someone can corroborate, that the guidance be changed to insert the "inlinePrebootCode" immediately after the app root element (so it works in most (all?) cases)

**Comment by jeffwhelpley** [comment]
Hi, @jotto. I will have a major refactor of preboot that will work better with v4 shortly. Stay tuned.

**Comment by kaynz** [comment]
@jeffwhelpley That sounds great! Do you have an ETA for us?

**Comment by chrisnassouri** [comment]
@jeffwhelpley any ETA on the refactor for v4?

**Comment by jeffwhelpley** [comment]
@chrisnassouri sorry about the delay. work projects have been eating into my fun open source time ;-)   I will get something out for this by next week.

**Comment by OEvgeny** [comment]
Is there some guide to set up current preboot with ng4 or should I wait patiently for new preboot version to use it with ng4?

Thank you!

**Comment by jeffwhelpley** [comment]
@OEvgeny so, the current version of preboot definitely works with ng4 (I have it working locally), but unfortunately there is no guide. You sort of have to hack it yourself using the info from the README: https://github.com/angular/preboot

This works perfectly fine, but the big issue is that the developer ergonomics for using this are totally gross since you need to essentially hack some JS outside the world of Angular. The only thing that will be different with the ng4 update to preboot that is coming will be some sugar on top so you can add preboot as an NgModule. 

Apologies this is taking me so long. Work is crazy right now, but I am still planning on trying to get this out by next week.

**Comment by OEvgeny** [comment]
@jeffwhelpley No need to apologise. It's totally ok. Thank you for response and for great work done!

**Comment by jotto** [comment]
I integrated preboot into https://www.prerender.cloud/ and it's working great for Angular 2 and 4. cmd+f for preboot on https://www.prerender.cloud/documentation if you want to try it (you just add `prerendercloud-preboot-app-root` as an attr to your app root.

**Comment by jeffwhelpley** [comment]
@jotto please try out v 5.0.0-rc.1 that I just relesed. You can read about it here: https://github.com/angular/preboot

Please let me know if that works for you.

**Comment by chrisnassouri** [comment]
@jeffwhelpley sick! thanks, i'll try this out

**Comment by jeffwhelpley** [comment]
@chrisnassouri note that we are up to `5.0.0-rc.10` after a flurry of fixes and other updates. I am going to close this issue because I am pretty sure this should be resolved now, but let me know if you are still having issues.

**Comment by schippie** [comment]
@jeffwhelpley This sadly for me is still not working when using AUX routes. I have had it happen now that the second `router-outlet` isn't available yet when it fires meaning inputs etc. that are located within my `router-outlet (popup)` (which acts as a modal) are not seen nor handled.

**Comment by schippie** [comment]
@jeffwhelpley the same thing happens after de application has been loaded. I was able to fix the loading problem by changing the init function within the preboot.js inline script:

```javascript
function init(opts, win) {
    var theWindow = (win || window);
    // add the preboot options to the preboot data and then add the data to
    // the window so it can be used later by the client
    var data = theWindow.prebootData = {
        opts: opts,
        listening: true,
        apps: [],
        listeners: []
    };
    // start up preboot listening as soon as the DOM is ready
	document.addEventListener("DOMContentLoaded", function(event) {
		start(data);
	});
}
```

Now the next problem is that once it starts up it again doesn't wait for my AUX route to be visible. The funny thing is though that the `focus` method within the `cleanup` method (which is triggered after a timeout) does work properly.

**Comment by jeffwhelpley** [comment]
Hey, so with `preboot@5.0.0-rc.12` that just got published I modified the browser module so it [waits until the application is stable](https://github.com/angular/preboot/blob/master/src/browser/browser-preboot.module.ts#L20) before running `replayAll()`. Let me know if that helps.
