### ISSUE TITLE
notSupportedError on event creation for certain events in IE 11

### ISSUE THREAD

**Issue by tstirrat15** [angular/preboot#29]
* **I'm submitting a ...**
bug report

* **Which parts of preboot are affected by this issue?**
client side

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I received a Sentry error for `notSupportedError` shortly after implementing preboot on my project. All of the errors came from IE11. After doing some research, it seems like it's an issue with IE11 not supporting certain `createEvent` calls. I haven't found documentation on which calls are and aren't supported, but I figured I'd let you know about this.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
I don't have reproduction steps, on account of not having IE to run against and being unable to find that documentation.

* **What is the expected behavior?**
No error.

* **What is the motivation / use case for changing the behavior?**
Errors!

* **Please tell us about your environment:**

- Browser: IE 11 | Safari XX ]
- OS: Windows

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
See above.

This was the stackOverflow page that I found that had me thinking what I wrote above:
https://stackoverflow.com/questions/23142816/how-to-resolve-the-javascript-error-of-ckeditor-in-ie-11

**Comment by jeffwhelpley** [comment]
Hi, @tstirrat15. Can you send me the stack trace from Sentry? Preboot doesn't actually use `createEvent()`. It uses `dispatchEvent()` which I believe should be supported.

**Comment by tstirrat15** [comment]
Stack trace:
```javascript
null: NotSupportedError
  at clientNode(~/preboot/__dist/preboot_browser.js:83:0)
```
which references this code:
```javascript
        }
        // now dispatch events and whatnot to the client node
        clientNode.checked = serverNode.checked ? true : undefined;
        clientNode.selected = serverNode.selected ? true : undefined;
        clientNode.value = serverNode.value;
        clientNode.dispatchEvent(event);
    }
    /**
     * Hide the server buffer and show the client buffer
     */
    function switchBuffer(window, appData) {
```
User agent string:
```
Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0;
Touch; rv:11.0; IEMobile/11.0; Microsoft;
Lumia 640 LTE) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537
```
I just realized too that the notSupportedErrors coming from non-mobile versions of IE 11 don't have attached stack traces (something something sentry error processing event), so I can't actually say for sure that they're coming from Preboot. They did only show up after implementing preboot.

**Comment by jeffwhelpley** [comment]
@tstirrat15 can you try out the latest preboot (version `5.0.0-rc.10`)? We are still using the same dispatchEvent, but according to this it is supported by IE 11:

http://caniuse.com/#feat=dispatchevent

**Comment by tstirrat15** [comment]
@jeffwhelpley I just read the bit about the latest Preboot release being Angular-specific. I'm using Preboot on top of a React stack, so it sounds like updating won't work?

**Comment by jeffwhelpley** [comment]
Hi, @tstirrat15, I am going to split preboot into two different repos/projects. Sorry for not communicating this clearly. This repo will only be dedicated to the Angular version. I will have the non-Angular version out in a separate repo and package by next week.

**Comment by tstirrat15** [comment]
Oh! Right on! Please keep me posted.

**Comment by jeffwhelpley** [comment]
Just wanted to let everyone know current status. Work has been insane the past week, so progress is slow but I did figure out a really good way to keep the project unified while still enabling usage without any Angular dependencies. Basically I am going to do a minor refactor so that the core guts remain dependency and there is just a separate import paths. So, for example, something like:

```
// angular-specific server side preboot
import { ServerPrebootModule } from 'preboot/server';

// angular-specific browser side preboot
import { BrowserPrebootModule } from 'preboot/browser';

// for non-angular project there is no server side. simply include dist/preboot.min.js in your server view and then add right below it a call to init(prebootOptions)

// for non-angular projects on the client side you simply do
import { EventReplayer } from 'preboot';
const replayer = new EventReplayer();
replayer.replayAll();

```

I can probably add some more sugar on top of that to make non-angular usage even easier, but let me know if there are any thoughts here.

**Comment by tstirrat15** [comment]
This looks totally awesome. Thank you for your work!

**Comment by jeffwhelpley** [comment]
OK, just pushed in `preboot@5.0.0-rc.12` which has a non-Angular interface. Please look at the [README](README.md) for details on how to use it and let me know if there are any questions.
