### ISSUE TITLE
Error after click on checkbox

### ISSUE THREAD

**Issue by thebarada** [angular/preboot#33]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Error in console after click on checkbox
![angularuniversal 2017-06-05 10-24-58](https://cloud.githubusercontent.com/assets/9532838/26774602/b0903442-49d9-11e7-8cbb-23e8dbfb5c8a.png)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Create app with one or more checkboxes and try to check preboot clicking on it

* **What is the expected behavior?**
No errors in console, correct replay click on checkbox event

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Browser: [all | **Chrome XX** | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript 2.3.3 | ES6/7 | ES5 ]
- OS:  [all | **Mac OS X** | Windows | Linux ]
- Platform: [all | **NodeJs** | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jeffwhelpley** [comment]
Ah, right. Will have fix for this in the next release.

**Comment by thebarada** [comment]
hey guys
Could you say presumably when will next release?

**Comment by jeffwhelpley** [comment]
Sorry for the delay. This issue is fixed now with `5.0.0-rc.11`.

**Comment by thebarada** [comment]
@jeffwhelpley 
thnx a lot
but when you planned release stable version (I mean non rc)?

**Comment by jeffwhelpley** [comment]
Ah, yes. We are just about ready. The last major thing is that I need to add an export for non-angular users per #29 

I hope to have that wrapped up by next week.

**Comment by thebarada** [comment]
@jeffwhelpley 
ok, it is great
Looking forward to release)
