### ISSUE TITLE
Typescript compiler throws 'Cannot find require' error

### ISSUE THREAD

**Issue by chaosmonster** [angular/preboot#36]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [x] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**

*bug*

* **What is the current behavior?**

I get an error and can't build the app.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Follow the steps of this article https://medium.com/@evertonrobertoauler/angular-4-universal-app-with-angular-cli-db8b53bba07d to create a ssr. Add preboot following the instruction of the readme.md (Will provide a demo repo later this week if necessary)

* **Please tell us about your environment:**

- Browser: [--]
- Language: [TypeScript 2.3.4]
- OS:  [Mac OS X]
- Platform: [NodeJs 7.8.0]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

When I add `declare var require: any;` to the top of `server/inline.preboot.code.ts` The error is solved. Seems like my attemp to compile my app with ngc also compiles server.ts (because of the import in app.server.module.ts) instead of taking the precompiled files

**Comment by jeffwhelpley** [comment]
Interesting. Thanks for submitting this, @chaosmonster. I will put out a fix later this week.

**Comment by Prafful-p** [comment]
facing same problem.
any solution or update on it @jeffwhelpley

**Comment by jeffwhelpley** [comment]
Sorry, @Prafful-p, I got caught up with other work stuff this past week. I will have time this weekend.

**Comment by not-only-code** [comment]
Check this out:
https://stackoverflow.com/questions/31173738/typescript-getting-error-ts2304-cannot-find-name-require

**Comment by jeffwhelpley** [comment]
OK, so it is true that if you had `@types/node` as a dev dependency in your project it would fix this, but I added `declare var require: any;` regardless so that the user doesn't necessarily have to do this. Please re-test with the 5.0.0 release and let me know.

**Comment by chaosmonster** [comment]
Thanks
