### ISSUE TITLE
Cleanup PrebootOverlay after preboot finishes.

### ISSUE THREAD

**Issue by dneeleman** [angular/preboot#37]
**Note: for support questions, please use the Universal Slack Channel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
Request a feature

* **What is the current behavior?**
When prebooting finishes, it leaves a prebootOverlay div behind. I think this should be cleaned up if this has no purpose after preboot is done.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Not a bug

* **What is the expected behavior?**
 I think this should be cleaned up if this has no purpose after preboot is done.

* **What is the motivation / use case for changing the behavior?**
Cleaner HTML document after preboot

* **Please tell us about your environment:**

- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jeffwhelpley** [comment]
This is fixed with `5.1.4`

**Comment by dneeleman** [comment]
Hi @jeffwhelpley, not entirely sure, but it seems to be back again.

Included is the script that is still in the header of our application.
`<script>(function () {


        function waitUntilReady(data, win) {
            var /** @type {?} */ theWindow = /** @type {?} */ ((win || window));
            var /** @type {?} */ document = /** @type {?} */ ((theWindow.document || {}));
            if (document.body) {
                start(data);
            }
            else {
                setTimeout(function () {
                    waitUntilReady(data);
                }, 10);
            }
        }

        function start(prebootData, win) {
            var /** @type {?} */ theWindow = /** @type {?} */ ((win || window));
            // only start once
            if (theWindow.prebootStarted) {
                return;
            }
            else {
                theWindow.prebootStarted = true;
            }
            var /** @type {?} */ document = /** @type {?} */ ((theWindow.document || {}));
            var /** @type {?} */ opts = prebootData.opts || (/** @type {?} */ ({}));
            var /** @type {?} */ eventSelectors = opts.eventSelectors || [];
            // create an overlay that can be used later if a freeze event occurs
            prebootData.overlay = createOverlay(document);
            // get an array of all the root info
            var /** @type {?} */ appRoots = prebootData.opts ? getAppRoots(document, prebootData.opts) : [];
            // for each app root
            appRoots.forEach(function (root) {
                // we track all events for each app in the prebootData object which is on
                // the global scope
                var /** @type {?} */ appData = /** @type {?} */ ({root: root, events: []});
                if (prebootData.apps) {
                    prebootData.apps.push(appData);
                }
                // loop through all the eventSelectors and create event handlers
                eventSelectors.forEach(function (eventSelector) {
                    return handleEvents(prebootData, appData, eventSelector);
                });
            });
        }

        function createOverlay(document) {
            var /** @type {?} */ overlay = undefined;
            if (document.createElement) {
                overlay = document.createElement('div');
                if (overlay.setAttribute) {
                    overlay.setAttribute('id', 'prebootOverlay');
                    overlay.setAttribute('style', 'display:none;position:absolute;left:0;' + 'top:0;width:100%;height:100%;z-index:999999;background:black;opacity:.3');
                    if (document.body && document.body.appendChild) {
                        document.body.appendChild(overlay);
                    }
                }
            }
            return overlay;
        }

        function getAppRoots(document, opts) {
            var /** @type {?} */ roots = [];
            // loop through any appRoot selectors to add them to the list of roots
            if (opts.appRoot && opts.appRoot.length) {
                var /** @type {?} */ baseList = [];
                var /** @type {?} */ appRootSelectors = baseList.concat(opts.appRoot);
                appRootSelectors.forEach(function (selector) {
                    return roots.push({serverSelector: selector});
                });
            }
            // now loop through the roots to get the nodes for each root
            roots.forEach(function (root) {
                if (document.querySelector) {
                    root.serverNode = /** @type {?} */ (document.querySelector(root.serverSelector));
                }
                root.clientSelector = root.clientSelector || root.serverSelector;
                if (root.clientSelector !== root.serverSelector) {
                    // if diff selectors, then just get the client node
                    if (document.querySelector) {
                        root.clientNode = /** @type {?} */ (document.querySelector(root.clientSelector));
                    }
                }
                else if (opts.buffer) {
                    // if we are doing buffering, we need to create the buffer for the client
                    root.clientNode = createBuffer(root);
                }
                else {
                    // else the client root is the same as the server
                    root.clientNode = root.serverNode;
                }
                // if no server node found, log error
                if (!root.serverNode) {
                    console.log('No server node found for selector: ' + root.serverSelector);
                }
            });
            return roots;
        }

        function handleEvents(prebootData, appData, eventSelector) {
            var /** @type {?} */ serverRoot = appData.root.serverNode;
            // don't do anything if no server root
            if (!serverRoot) {
                return;
            }
            // get all nodes under the server root that match the given selector
            var /** @type {?} */ nodes = serverRoot.querySelectorAll(eventSelector.selector);
            // don't do anything if no nodes found
            if (!nodes) {
                return;
            }
            var _loop_1 = function (node) {
                eventSelector.events.forEach(function (eventName) {
                    // get the appropriate handler and add it as an event listener
                    var /** @type {?} */ handler = createListenHandler(prebootData, eventSelector, appData, node);
                    if (node.addEventListener) {
                        node.addEventListener(eventName, handler);
                    }
                    // need to keep track of listeners so we can do node.removeEventListener()
                    // when preboot done
                    if (prebootData.listeners) {
                        prebootData.listeners.push({
                            node: /** @type {?} */ (node),
                            eventName: eventName,
                            handler: handler
                        });
                    }
                });
            };
            // we want to add an event listener for each node and each event
            for (var _i = 0, _a = Array.from(nodes); _i < _a.length; _i++) {
                var node = _a[_i];
                _loop_1(node);
            }
        }

        function createListenHandler(prebootData, eventSelector, appData, node) {
            var /** @type {?} */ CARET_EVENTS = ['keyup', 'keydown', 'focusin', 'mouseup', 'mousedown'];
            var /** @type {?} */ CARET_NODES = ['INPUT', 'TEXTAREA'];
            return function (event) {
                var /** @type {?} */ root = appData.root;
                var /** @type {?} */ eventName = event.type;
                // if no node or no event name or not listening, just return
                if (!node || !eventName) {
                    return;
                }
                // if key codes set for eventSelector, then don't do anything if event
                // doesn't include key
                var /** @type {?} */ keyCodes = eventSelector.keyCodes;
                if (keyCodes && keyCodes.length) {
                    var /** @type {?} */ matchingKeyCodes = keyCodes.filter(function (keyCode) {
                        return event.which === keyCode;
                    });
                    // if there are not matches (i.e. key entered NOT one of the key codes)
                    // then don't do anything
                    if (!matchingKeyCodes.length) {
                        return;
                    }
                }
                // if for a given set of events we are preventing default, do that
                if (eventSelector.preventDefault) {
                    event.preventDefault();
                }
                // if an action handler passed in, use that
                if (eventSelector.action) {
                    eventSelector.action(node, event);
                }
                // get the node key for a given node
                var /** @type {?} */ nodeKey = getNodeKeyForPreboot({root: root, node: node});
                // if event on input or text area, record active node
                if (CARET_EVENTS.indexOf(eventName) >= 0 && CARET_NODES.indexOf(node.tagName ? node.tagName : '') >= 0) {
                    prebootData.activeNode = {
                        root: root,
                        node: node,
                        nodeKey: nodeKey,
                        selection: getSelection(/** @type {?} */ (node))
                    };
                }
                else if (eventName !== 'change' && eventName !== 'focusout') {
                    prebootData.activeNode = undefined;
                }
                // if we are freezing the UI
                if (eventSelector.freeze) {
                    var /** @type {?} */ overlay_1 = /** @type {?} */ (prebootData.overlay);
                    // show the overlay
                    if (overlay_1 && overlay_1.style) {
                        overlay_1.style.display = 'block';
                    }
                    // hide the overlay after 10 seconds just in case preboot.complete() never
                    // called
                    setTimeout(function () {
                        if (overlay_1 && overlay_1.style) {
                            overlay_1.style.display = 'none';
                        }
                    }, 10000);
                }
                // we will record events for later replay unless explicitly marked as
                // doNotReplay
                if (!eventSelector.noReplay) {
                    appData.events.push({node: node, nodeKey: nodeKey, event: event, name: eventName});
                }
            };
        }

        function getSelection(node) {
            node = node || /** @type {?} */ ({});
            var /** @type {?} */ nodeValue = node.value || '';
            var /** @type {?} */ selection = {
                start: nodeValue.length,
                end: nodeValue.length,
                direction: 'forward'
            };
            // if browser support selectionStart on node (Chrome, FireFox, IE9+)
            try {
                if (node.selectionStart || node.selectionStart === 0) {
                    selection.start = node.selectionStart;
                    selection.end = node.selectionEnd ? node.selectionEnd : 0;
                    selection.direction = node.selectionDirection ? node.selectionDirection : '';
                }
            }
            catch (/** @type {?} */ ex) {
            }
            return selection;
        }

        function createBuffer(root) {
            var /** @type {?} */ serverNode = root.serverNode;
            // if no rootServerNode OR the selector is on the entire html doc or the body
            // OR no parentNode, don't buffer
            if (!serverNode || !serverNode.parentNode || root.serverSelector === 'html' || root.serverSelector === 'body') {
                return /** @type {?} */ (serverNode);
            }
            // create shallow clone of server root
            var /** @type {?} */ rootClientNode = /** @type {?} */ (serverNode.cloneNode(false));
            if (rootClientNode) {
                // we want the client to write to a hidden div until the time for switching
                // the buffers
                if (rootClientNode.style) {
                    rootClientNode.style.display = 'none';
                }
                // insert the client node before the server and return it
                if (serverNode.parentNode.insertBefore) {
                    serverNode.parentNode.insertBefore(rootClientNode, serverNode);
                }
            }
            // return the rootClientNode
            return rootClientNode;
        }

        function getNodeKeyForPreboot(nodeContext) {
            var /** @type {?} */ ancestors = [];
            var /** @type {?} */ root = nodeContext.root;
            var /** @type {?} */ node = nodeContext.node;
            var /** @type {?} */ temp = node;
            // walk up the tree from the target node up to the root
            while (temp && temp !== root.serverNode && temp !== root.clientNode) {
                ancestors.push(temp);
                temp = /** @type {?} */ (temp.parentNode);
            }
            // note: if temp doesn't exist here it means root node wasn't found
            if (temp) {
                ancestors.push(temp);
            }
            // now go backwards starting from the root, appending the appName to unique
            // identify the node later..
            var /** @type {?} */ name = node.nodeName || 'unknown';
            var /** @type {?} */ key = name + '_' + root.serverSelector;
            var /** @type {?} */ len = ancestors.length;
            for (var /** @type {?} */ i = len - 1; i >= 0; i--) {
                temp = ancestors[i];
                if (temp.childNodes && i > 0) {
                    for (var /** @type {?} */ j = 0; j < temp.childNodes.length; j++) {
                        if (temp.childNodes[j] === ancestors[i - 1]) {
                            key += '_s' + (j + 1);
                            break;
                        }
                    }
                }
            }
            return key;
        }


        (function init(opts, win) {
                var /** @type {?} */ theWindow = /** @type {?} */ ((win || window));
                // add the preboot options to the preboot data and then add the data to
                // the window so it can be used later by the client
                var /** @type {?} */ data = (theWindow.prebootData = /** @type {?} */ ({
                    opts: opts,
                    listening: true,
                    apps: [],
                    listeners: []
                }));
                // start up preboot listening as soon as the DOM is ready
                waitUntilReady(data);
            }
        )({
            "buffer": true,
            "minify": true,
            "eventSelectors": [{
                "selector": "input,textarea",
                "events": ["keypress", "keyup", "keydown", "input", "change"]
            }, {"selector": "select,option", "events": ["change"]}, {
                "selector": "input",
                "events": ["keyup"],
                "preventDefault": true,
                "keyCodes": [13],
                "freeze": true
            }, {
                "selector": "form",
                "events": ["submit"],
                "preventDefault": true,
                "freeze": true
            }, {
                "selector": "input,textarea",
                "events": ["focusin", "focusout", "mousedown", "mouseup"],
                "noReplay": true
            }, {"selector": "button", "events": ["click"], "preventDefault": true, "freeze": true}],
            "appRoot": "app"
        })
    })()</script>`

**Comment by jeffwhelpley** [comment]
@dneeleman can you try updating to our latest beta version `6.0.0-beta.0`?
