### ISSUE TITLE
Does preboot support Angular 4?

### ISSUE THREAD

**Issue by m98** [angular/preboot#39]
* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] question

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [x] docs
- [ ] tests

I think the title is clear, and I want to ask if Preboot supports Angular 4 (or users should just use `platform-server`) then we need to specify that in docs, or talking about how to implement it with different versions of Angular (actually preboot seems to work with any front-end framework but still need some explanation)

**Comment by iuliust** [comment]
I'm wondering the same thing.
[Here's my repo ](https://github.com/iuliust/semper)
Never managed to get preboot to work 😢

**Comment by yunus-alkan** [comment]
me neither

**Comment by LucasPaganini** [comment]
I would also like to see a boilerplate of Preboot with angular 4 the way they did in the Universal Rendering Story: https://github.com/angular/angular-cli/wiki/stories-universal-rendering

**Comment by jeffwhelpley** [comment]
Sure thing @LucasPaganini. I can throw something together later this weekend.

**Comment by jeffwhelpley** [comment]
OK, so I have an example of this working here:

https://github.com/jeffwhelpley/universal-starter-preboot

I basically just took the latest universal-starter and tweaked it a little bit.

**Comment by CSchulz** [comment]
The important changes are the new version of preboot (5.1.4) and resolve extension `".js", ".ts"`.

Is it possible to replace the hard-coded timeout?

**Comment by jeffwhelpley** [comment]
@CSchulz which setTimeout?

**Comment by CSchulz** [comment]
Forget about it. 😆 
I haven't seen that it is used for demonstration reasons. In this moment I want to remove the question from my comment.
