### ISSUE TITLE
Add lifecycle hook for BufferSwitchComplete

### ISSUE THREAD

**Issue by jackbliss99** [angular/preboot#42]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**

Request a feature

* **What is the current behavior?**

The preboot module switches from the server view to the client view silently

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

Allow for detection in the client app for transition from server view to client view

* **What is the motivation / use case for changing the behavior?**

Writing a carousel component that requires calculating the size of the component at the point of rendering. As the component is (very usefully) hidden, it has no size, so as the component initialises it returns a width of 0.

* **Please tell us about your environment:**

- Browser: [all]
- Language: [all]
- OS:  [all]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jackbliss99** [comment]
In case anyone has come here with a similar problem - i solved this by adding in an extra wrapping div and using a percentage based approach.

**Comment by jeffwhelpley** [comment]
Ah, this is interesting. So, there must be something displayed on the server view, right? I suggest that you have that initial displayed in the client view as well and then only do the carosel calculation once preboot has switched the buffers.

**Comment by jackbliss99** [comment]
i suppose that's exactly my problem - i don't know how to delay the calculation until the preboot switches. is there a way to trigger off the switch? is there a way to detect the switch? another solution i saw online was to use a setInterval to keep checking to see if the element has width yet, but as hacks go that's extreeeeemely hackey.

**Comment by jeffwhelpley** [comment]
The setInterval thing would work, but that is hacky. The solution is to add a new event to preboot that you can listen for. I will add that.

**Comment by jackbliss99** [comment]
that's fantastic, thank you. the library is excellent, by the way!

**Comment by jeffwhelpley** [comment]
OK, check out `5.1.4`. After preboot is complete, an event called `PrebootComplete` is dispatched on `window.document`. So you can now do this:

```
window.document. addEventListener('PrebootComplete', function () {
  // do stuff here
});
```
