### ISSUE TITLE
feat(csp): add nonce to preboot to avoid CSP conflict

### ISSUE THREAD

**Issue by CaerusKaru** [angular/preboot#45]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [ ] client side
- [x] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**

Bug report

* **What is the current behavior?**

Currently preboot injects a script into the HTML which is blocked from running if the CSP does not contain `unsafe-inline`.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Load preboot, add CSP header `script-src: 'self' 'unsafe-eval'`, receive error

* **What is the expected behavior?**

Preboot should add a nonce to its script, randomly generated on each load

* **What is the motivation / use case for changing the behavior?**

It allows for better security in writing CSP rules to not have to accommodate preboot

**Comment by CaerusKaru** [comment]
Realistically, the only way to implement this is if preboot pulls in an Optional provider that can be injected into the app when generated on the server

**Comment by CaerusKaru** [comment]
cc @jeffwhelpley

**Comment by jeffwhelpley** [comment]
@CaerusKaru thanks for bringing this to my attention. I had no idea this was a problem. I will put in a fix for this later in the week.

**Comment by CaerusKaru** [comment]
@jeffwhelpley I already submitted a PR under #46 if you want to take a look. It works by allowing users to inject a NONCE token (since the server has to configure it to attach to the headers). Instructions for use are also in the PR

**Comment by CaerusKaru** [comment]
@jeffwhelpley I hadn't thought of this at the time, but do you want me to document this feature somewhere? I could add it to the README or a separate entry in a docs folder?

**Comment by jeffwhelpley** [comment]
OK, merged that in and added change on top of that to fix broken e2e tests (i.e. because need default value for nonce) and publish new version. Let me know if you see any other issues.

**Comment by CaerusKaru** [comment]
@jeffwhelpley The nonce is now undefined when the HTML is compiled, meaning that the e2e fix breaks the functionality. Can the e2e app be responsible for generating its own nonce, outside of the server-preboot-module?

**Comment by CaerusKaru** [comment]
@jeffwhelpley Ok I fixed this issue and can prepare another PR, but should I add some documentation somewhere? Do you prefer tacking it on to the README or adding a separate file?

**Comment by jeffwhelpley** [comment]
Yes, do another PR and just add a section to the README. Also, feel free to increment the patch version number in your PR and I will publish it once I test it out. Thanks!

**Comment by CaerusKaru** [comment]
@jeffwhelpley PR submitted as #47. Basically the default nonce you added wasn't getting overridden (and since it wasn't typed as a string, it also wasn't getting rendered). I added a DI workaround since NgModules don't allow for optional dependencies. Just injecting the token by itself (as in the original) and having the e2e app provide its own for testing would force users to always provide the token or get an error (as e2e testing thoughtfully alerted us). It all works now, e2e and all.
