### ISSUE TITLE
refactor: change project structure to Angular Library format

### ISSUE THREAD

**Issue by CaerusKaru** [angular/preboot#49]
Currently the package is built in such a way that a lot of files are duplicated as both ts and js files. The project should be refactored to use a build process similar to Angular core, Material, and Flex-Layout, with multiple bundles for ES5 and ES2015.

At the very least, it would allow for top-level imports instead of `import * from 'preboot/src'` as currently required.

**Comment by CaerusKaru** [comment]
For reference, the PR that Flex-Layout used for initial change: https://github.com/angular/flex-layout/pull/342

And the commit for Flex-Layout introducing ES5 and ES2015 bundles: https://github.com/angular/flex-layout/commit/cc12733062c363c4121165877227782b7e80570e

**Comment by jeffwhelpley** [comment]
@CaerusKaru you should definitely not be doing `import * from 'preboot/src'`. You should be doing `import * from 'preboot/server'` for the server side or `import * from 'preboot/browser'` for the client side. I am aware of the way other angular libs are setup, but the key difference is that preboot is set up for non-angular projects to use it without any angular dependencies. There are a number of react and other non-angular projects that use this library. That is the cause of some of the quirky setup. Let me know, though, if you can think of a way to modify the structure while still allowing for non-angular users.

**Comment by sylvaindumont** [comment]
With the latest @angular/cli changes (https://github.com/angular/angular-cli/commit/6f255acd1b30ab8122a562660d3dfeb0b5ec5681)
ng test throw `node_modules/preboot/browser.ts is not part of the compilation output.`
Manually removing .ts files from node_module/preboot fix the issue.
preboot is the only module to throw these errors, material and flex-layout works fine, it seems that the current library format works for react but no longer for angular :p

**Comment by CaerusKaru** [comment]
Would this be fixed by adding a `@types/preboot`, and then only shipping the `.js` files in the npm distribution?

**Comment by jeffwhelpley** [comment]
@CaerusKaru actually, that is a good idea I didn't think about. I am slammed this week preparing for AngularConnect, but will think about this over the weekend. I have never published anything to @types so I will have to do some research to see how to potentially set up the project for that.

**Comment by CaerusKaru** [comment]
@jeffwhelpley On further reflection, we don't need @types, because we're bundling the `*.d.ts` files with all of the output. What we really need to do is exclude the `*.ts` files from the package distribution.

I've submitted a PR that does this, and also incorporates the changes allowing for top-level imports throughout the package, but it comes at the cost of importing from `preboot/server` or `preboot/browser` directly. I can make a small change that restores that functionality, but it would be a build headache, and plus I don't think it should be encouraged behavior anyway.

**Comment by CaerusKaru** [comment]
To provide an update on the Angular Library front, the work is proceeding over on [this branch](https://github.com/CaerusKaru/preboot/tree/lib). It provides bundled versions of preboot and the necessary typings, similar to how Material and Flex-Layout handle packages. It also should keep compatibility with react and other frameworks and allow for top-level imports.

If anyone wants to jump in, the issues I'm currently trying to resolve revolve around instantiating and running the EventReplayer when the browser module tries to bootstrap (this is probably related to AOT in some way and evaluating `window` at compile time). Also the nonce feature no longer works for some reason, despite providing it as a platform-level provider.

The new version is essentially the same, except the minify feature has been gutted (minification should be done by the client anyway -- the angular-cli does this by default), and the Server and Browser modules have been combined into one. This is achieved because the server instantiation is tied into the platformServer render hook, and the browser instantiation has window checks. 

cc @jeffwhelpley Any thoughts on this? I'd be happy to discuss offline if you want

**Comment by jeffwhelpley** [comment]
@CaerusKaru Hey, at a quick glance this looks good. I am on my way to AngularConnect right now. I will try this out in more detail on Thursday after my talk. 

At a high level, tough, I agree with the direction and we can definitely get in something along these lines within the next week.
