### ISSUE TITLE
Dist preboot_inline from preboot_node incorrect

### ISSUE THREAD

**Issue by paullryan** [angular/preboot#5]
Looks like a build step is breaking when creating dist/preboot_node.js it's including the src relative path of `require('../inline/preboot_inline')` at https://github.com/angular/preboot/blob/master/dist/preboot_node.js#L2. 

It should instead have been resolved to the dist relative path of `require('./preboot_inline')`

**Comment by jeffwhelpley** [comment]
Ah, yes, that is an issue. I mistakenly was publishing preboot_node to the dist root dir. I have now corrected the issue. Please get the latest.
