### ISSUE TITLE
Server module exceedes call stack

### ISSUE THREAD

**Issue by TitanNano** [angular/preboot#54]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [X] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [X] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**

> RangeError: Maximum call stack size exceeded
>     at _createProviderInstance$1 (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9531:35)
>     at resolveNgModuleDep (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9520:17)
>     at _createClass (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9561:29)
>     at _createProviderInstance$1 (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9535:26)
>     at resolveNgModuleDep (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9520:17)
>     at _createClass (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9561:29)
>     at _createProviderInstance$1 (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9535:26)
>     at resolveNgModuleDep (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9520:17)
>     at _createClass (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9561:29)
>     at _createProviderInstance$1 (/home/ubuntu/stack/angular/node_modules/@angular/core/bundles/core.umd.js:9535:26)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
use the ServerModule with `recordEvents({ appRoot: 'app-root' })`

* **What is the expected behavior?**
angular should be able to bootstrap without errors

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Browser: all
- Language: TypeScript
- OS:  Mac OS X | Linux
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by TitanNano** [comment]
We only get this error on our actual server and not on the dev machine. We can't tell why the call stack is exceeded on the server though.

**Comment by CaerusKaru** [comment]
Can you provide a minimal reproduction repo?

**Comment by TitanNano** [comment]
We didn't create a reproduction repo yet, but we are still on it.

**Comment by TitanNano** [comment]
upgrading to v6 solved this issue for us.
