### ISSUE TITLE
Is compatible Angular 5???

### ISSUE THREAD

**Issue by Madebyivan** [angular/preboot#55]
Is compatible Angular 5???

**Comment by CaerusKaru** [comment]
Yes, can be closed.

**Comment by Madebyivan** [comment]
Not so fast baquero...

ng new project
npm i preboot --save

And only... app.module.ts...

import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserPrebootModule } from 'preboot/browser';

import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    BrowserPrebootModule.replayEvents()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

And... ng serve...
ERROR in ./node_modules/preboot/browser.ts

<img width="1337" alt="screen shot 2017-11-15 at 7 02 33 pm" src="https://user-images.githubusercontent.com/242960/32852248-9c59c338-ca37-11e7-835e-87e563687f54.png">

**Comment by CaerusKaru** [comment]
Duplicate of #52

**Comment by Madebyivan** [comment]
Thanks!
