### ISSUE TITLE
https api url fail in ssr for meta tags

### ISSUE THREAD

**Issue by ranjitnadar** [angular/preboot#56]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [x] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
For meta information we pulling from api.
Using http SSR working perfect
Using https SSR not working.

Any help

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by CaerusKaru** [comment]
If this is actually an issue relating exclusively to **preboot**, please provide a minimal reproduction repo. If it's related to SSR in general, a better avenue for issues is the angular/universal repo.

**Comment by CaerusKaru** [comment]
Closing as no followup was provided.
