### ISSUE TITLE
[Issue] when browser refresh, rendered DOM is gone

### ISSUE THREAD

**Issue by gmanio** [angular/preboot#57]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [x] server side
- [x] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **What is the current behavior?**
Chrome 60: browser refresh

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
https://github.com/gmanio/ng-ssr

* **What is the expected behavior?**
refresh well

**Comment by CaerusKaru** [comment]
Remove [this line](https://github.com/gmanio/ng-ssr/blob/64ffad7d2ffbb949bc72e6c2e363399990f88d0d/src/app/app.server.module.ts#L12) and everything should work.

**Comment by gmanio** [comment]
In chrome browser (latest version), 
clean refresh worked well, But just browser refresh doesn't work. ( Dom is gone )
Personally, I carefully think that this would be related replay events.

1. clone
2. yarn install
3. yarn build 
4. yarn build:ssr
5. ts-node server.ts
6. first rendering is well but refresh ( document empty )

**Comment by misticwonder** [comment]
I've also reproduce this bug https://github.com/misticwonder/preboot-bug1
- node version 8.9.0
- npm run build:ssr && npm run serve:ssr
- http://localhost:4000 

Issue:
The content of the page disappears in chrome browser when using preboot.
The problem is related to the browser cache.

**Comment by sylvaindumont** [comment]
Without `BrowserModule.withServerTransition({ appId: 'ssr-angular' })` in app.server.module.ts, the dom disappear too.
Removing it in app.module.ts too fix the issue, but prerendering throw 
`renderModule[Factory]() requires the use of BrowserModule.withServerTransition() to ensure
the server-rendered app can be properly bootstrapped into a client app.`

**Comment by CaerusKaru** [comment]
Turns out it's not a cache issue, preboot is working exactly as intended. The issue was that preboot was waiting too long to take over from the inline script (when delayed by a timer, this throws off app stability). PR #60 should resolve this, feel free to install from remote branch and test.

**Comment by CaerusKaru** [comment]
Due to issues described in the comments of #60, this is going to be partially reverted. In order to achieve the behavior from beta.1 in beta.2 (when it's published), you'll have to use @sylvaindumont's [workaround](https://github.com/angular/preboot/issues/57#issuecomment-350335133) and set `buffer` to `false`.

**Comment by CaerusKaru** [comment]
Please see updated comments [here](https://github.com/angular/preboot/pull/60#issuecomment-362866734) for the correct response to this issue after this is reverted in 6.0.0-beta.2
