### ISSUE TITLE
Component CSS Disappears from Components During Preboot

### ISSUE THREAD

**Issue by kblestarge** [angular/preboot#59]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [x] inline
- [ ] build process
- [ ] docs
- [ ] tests

My beautiful server-side rendered Angular 5 application (using Universal with a node express.js server) is having problems with styling during the bootstrap (preboot) phase. The global CSS stylesheet seems to be fine, but the component-specific styles disappear once bootstrapping begins.

This probably isn't the right way to report this issue, but please see my stackoverflow question for more details:
https://stackoverflow.com/questions/47701349/component-css-disappears-from-components-during-app-bootsrapping-with-preboot

**Comment by misticwonder** [comment]
It's the same issue https://github.com/angular/preboot/issues/58

**Comment by kblestarge** [comment]
Closing because we will track it here: [#58](https://github.com/angular/preboot/issues/58). 
Glad I'm not alone with this bug. Thanks @misticwonder.
