### ISSUE TITLE
preboot with appRoot being the root HTML tag

### ISSUE THREAD

**Issue by mickael-kerjean** [angular/preboot#6]
Hello,

I'm trying do make some basic seo with an angular application. 
My index.html is:
```
<!doctype html>
<html lang="en"></html>
```
The application root component from a universal perspective is the html component.

The issue is the preboot code is append after the closing html tag which makes preboot unavailable to the global scope:
```
<!doctype html>
<html>
 generated by universal
</html>
<div>
    <style>preboot css</style>
    <script>preboot js</script
</div>
```

In this case, it should generate:
```
<!doctype html>
<html>
 generated by universal
<div>
    <style>preboot css</style>
    <script>preboot js</script
</div>
</html>
```

Is there a trick to make it work?
I tried to load preboot_browser in the browser via the html component and call preboot.complete but I couldn't end up with something that actually work.

**Comment by jeffwhelpley** [comment]
Hi. I am in the middle of trying to integrate the latest preboot to the latest universal. If you want an interim workaround for your issue, do the following:

1. Turn preboot off in your universal settings (i.e. `preboot: false`)
2. Get the latest preboot (currently 4.0.3)
3. Literally just copy `dist/preboot_inline.min.js` into the head of your index.html
4. Right after the copied inline code, in the head section call ` prebootstrap().init(opts)`. You can see the available options in preboot 4 here: https://github.com/angular/preboot#options
4. Include the contents of `dist/preboot_browser.min.js` in your client side package (i.e. however you are referencing your angular app code.
5. After the client side angular finishes bootstraps, call `preboot.complete()`. The preboot object should be attached to the global window by the preboot_browser.min.js code.

Let me know if you have any questions. I will update this item once I publish the updated universal core lib with integration to preboot 4.

**Comment by jeffwhelpley** [comment]
OK, so preboot now works in the head tag. If you use the default Express Engine, it will still stick the script tag at the end of the body, but all  you have to do is mimic what is being done here:

https://github.com/angular/universal/blob/master/modules/express-engine/src/index.ts

But just put the inline preboot in the head.
