### ISSUE TITLE
new Event does not work in IE11, and unfortunately neither does the polyfill from MDN and this question: Internet Explorer 9, 10 & 11 Event constructor doesn't work, since they rely on document.createEvent.

### ISSUE THREAD

**Issue by dneeleman** [angular/preboot#64]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
A bug

* **What is the current behavior?**
'new Event' does not work in IE11, and unfortunately neither does the polyfill from MDN.
The error raised is: Object doesn't support this action

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Just launch the application on IE11 with buffer enabled.

* **What is the expected behavior?**
It should work for IE11 I think.

* **What is the motivation / use case for changing the behavior?**
It should work for IE11 I think.

* **Please tell us about your environment:**

- Browser: [ IE 11 ]
- Language: [ ES5 ]
- OS:  [ Windows ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work
https://stackoverflow.com/questions/41575405/event-constructor-in-worker-on-ie11

**Comment by dneeleman** [comment]
Either this or https://github.com/angular/preboot/issues/63 seems to crash on IE11 for our application. Result is 2 <app> tags, where the cleanup/replay with buffer seems to fail.

I'll try again if and when this is solved for older browsers.

**Comment by CaerusKaru** [comment]
@dneeleman Can you elaborate on that?
