### ISSUE TITLE
Rename noReplay to replay

### ISSUE THREAD

**Issue by mgol** [angular/preboot#69]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**

A feature (renaming an existing feature).

* **What is the current behavior?**

`PrebootModule.withConfig` accepts `noReplay` as a parameter, `false` by default.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

N/A

* **What is the expected behavior?**

The property should be named `replay` and be `true` by default, just like `buffer`.

* **What is the motivation / use case for changing the behavior?**

It's well established that negatives are more difficult to read, especially when assigned a negative value, creating a double negative. Current API is also inconsistent with the `buffer` option that is set to `true` by default.

* **Please tell us about your environment:**

N/A

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Preboot 6 requires a different way of importing inside of an Angular NgModule so people upgrading will have to change their imports anyway. That's a good opportunity to rename the confusingly named option.

cc @CaerusKaru as we talked about it outside of GitHub.

**Comment by CaerusKaru** [comment]
I'm ok with this while we're in the v6 beta period. cc @jeffwhelpley for his thoughts

**Comment by jeffwhelpley** [comment]
This is fine with me.

**Comment by CaerusKaru** [comment]
@mgol If you want to submit a PR for this, go ahead. Otherwise I can tackle this tomorrow.

**Comment by mgol** [comment]
@CaerusKaru This will conflict with your PR, won't it? I'd rather wait for it to land then.

**Comment by CaerusKaru** [comment]
Let's get this in to beta.3

**Comment by dneeleman** [comment]
@CaerusKaru Not to be impatient, but when is beta.3 scheduled?

**Comment by CaerusKaru** [comment]
@dneeleman It is currently unscheduled since this is the only open (low-priority) issue. Is there another problem that needs to be patched?

**Comment by dneeleman** [comment]
@CaerusKaru Not that I'm aware of. I'll patiently wait for the release of the next beta/stable release. Thanks for the hard work!

**Comment by CaerusKaru** [comment]
For the record, v6.0.0-beta.2 was released late last night.

**Comment by dneeleman** [comment]
@CaerusKaru Ah, I thought we already had a beta.2. But it was pulled or something. But I guess that was the case with beta.1. My bad.
