### ISSUE TITLE
Error: Cannot set property 'prebootData' of undefined  

### ISSUE THREAD

**Issue by amit-kumar27** [angular/preboot#92]
**Note: for support questions, please use the Universal Slack Channcel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [x] server side
- [ ] client side
- [ ] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **What is the current behavior?**
After adding preboot@6.0.0-beta.3, in my Angular@5.2.1 application, getting this error on SSR, 
'Uncaught TypeError: Cannot set property 'prebootData' of undefined'
<img width="1437" alt="screen shot 2018-09-22 at 3 06 02 pm" src="https://user-images.githubusercontent.com/12585912/45915890-b82c5200-be7a-11e8-8fd8-3e392390f1fe.png">

<img width="1431" alt="screen shot 2018-09-22 at 3 06 39 pm" src="https://user-images.githubusercontent.com/12585912/45915894-c2e6e700-be7a-11e8-9b70-b43a35802ae7.png">

<img width="1432" alt="screen shot 2018-09-22 at 3 07 15 pm" src="https://user-images.githubusercontent.com/12585912/45915900-cf6b3f80-be7a-11e8-925e-ff8165cf4bea.png">

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

I have added PrebootModule in my root.module.ts like this:-

```
import { BrowserModule } from "@angular/platform-browser";
import { PrebootModule } from 'preboot';
import { ServerTransition } from "./server-transition.module";
import { RootComponent } from "./root.component";
...

@NgModule({
  imports: [
    ...,
    BrowserModule.withServerTransition({ appId: 'ng-web-app' }),
    PrebootModule.withConfig({ appRoot: 'root'}),    // 'root' is the selector of root component
    ...

  ],
  declarations: [
    RootComponent,
    ...
  ]
})
export class RootModule {}
```

and my root.server.module.ts :- 

```
import {NgModule} from '@angular/core';
import { ServerModule } from '@angular/platform-server';
import {ModuleMapLoaderModule} from '@nguniversal/module-map-ngfactory-loader';
import { RouterModule } from '@angular/router';

import {RootModule} from '../client/root.module';
import {Root} from '../client/root.component';

@NgModule({
  imports: [
    RootModule,
    ServerModule,
    ModuleMapLoaderModule
  ],
  bootstrap: [Root],
  providers: []
})
export class RootServerModule {}

```

* **What is the expected behavior?**
This error should not occur and the transition between SSR and CSR should be smooth.

* **Please tell us about your environment:**

- Language: [TypeScript ]
- Platform: [ NodeJs | Angular-5.2.1 ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by CaerusKaru** [comment]
We do not support or have LTS for any other version other than the current beta and the version of Angular it supports (in this case 6.0.0-beta.6 and Angular v6). I apologize for the inconvenience this may cause, but this is a very small project. If you can reproduce the issue on the latest beta, this is definitely something we can look into.

**Comment by CaerusKaru** [comment]
Closing. We can open if a reproduction with latest beta is added.
