### ISSUE TITLE
Inline start function uses wrong 'currentScript'.

### ISSUE THREAD

**Issue by dneeleman** [angular/preboot#93]
**Note: for support questions, please use the Universal Slack Channel or https://gitter.im/angular/universal** 

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request

* **Which parts of preboot are affected by this issue?**
- [ ] server side
- [x] client side
- [x] inline
- [ ] build process
- [ ] docs
- [ ] tests

* **Do you want to request a *feature* or report a *bug*?**
report a *bug*

* **What is the current behavior?**
When loading an Angular 6 application with Preboot, the code inside the inline start function has a fallback for _document.currentScript. But within the function the variable is not used at all, resulting in an error in Internet Explorer 10 and 11 (what I have tested).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a GitHub repo.
Use `currentScript` instead of `_document.currentScript` on `serverNode.removeChild`.

* **What is the expected behavior?**
No errors in IE10 & IE11

* **What is the motivation / use case for changing the behavior?**
It breaks the application right now.

* **Please tell us about your environment:**

- Browser: IE 10 & IE11
- Language: all
- OS: all
- Platform: NodeJS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by dneeleman** [comment]
The issue has been fixed in #94. Closing this issue.

**Comment by CaerusKaru** [comment]
A new version has been published, it should be populated on NPM within the next few minutes. Thanks for catching this and cutting a PR!

**Comment by dneeleman** [comment]
@CaerusKaru I have seen it! Thank you, guys.
